version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit_app
    container_name: ConfluenceRagClient
    env_file:
      - .env
    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}"
    volumes:
      - .:/ConfluenceRag
    networks:
      - net

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    # set IS_PERSISTENT for to allow persistence on HTTP client
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    ports:
      - "${CHROMADB_PORT}:${CHROMADB_PORT}"
    networks:
      - net
  
  cronjob:
    image: test_cron
    container_name: cronjob
    env_file:
      - .env
    environment:
      - CHROMADB_PORT=8000
    networks:
      - net

volumes:
  chroma-data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge