version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit_app:latest
    container_name: ConfluenceRagClient
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/ConfluenceRag
    networks:
      - net

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    # set IS_PERSISTENT for to allow persistence on HTTP client
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  chroma-data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge